/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import gui.view.cadastros.CadastroArmadilha;
import gui.view.cadastros.CadastroEspecie;
import gui.view.consultas.ConsultaArmadilha;
import gui.view.consultas.ConsultaEspecie;

/**
 *
 * @author fabio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBCadEspecie = new javax.swing.JButton();
        jBCadArmadilha = new javax.swing.JButton();
        jBLancamento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLBarraDeStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMCadEspecie = new javax.swing.JMenuItem();
        jMCadArmadilha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMConsEspecie = new javax.swing.JMenuItem();
        jMConsArmadilha = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMRelatorio1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jBCadEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/butterfly-folder-icon.png"))); // NOI18N
        jBCadEspecie.setText("Cadastros Espécie");
        jBCadEspecie.setToolTipText("Opção de cadastro de espécies e sua familia");
        jBCadEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCadEspecieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCadEspecieMouseExited(evt);
            }
        });
        jBCadEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadEspecieActionPerformed(evt);
            }
        });

        jBCadArmadilha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/t-bird-icon.png"))); // NOI18N
        jBCadArmadilha.setText("Cadastro de Armadilha");
        jBCadArmadilha.setToolTipText("Cadastrar o tipo de Armadilha utilizada");
        jBCadArmadilha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCadArmadilhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCadArmadilhaMouseExited(evt);
            }
        });
        jBCadArmadilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadArmadilhaActionPerformed(evt);
            }
        });

        jBLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/image2993.png"))); // NOI18N
        jBLancamento.setText("Lançamentos");
        jBLancamento.setToolTipText("Lançar a Armadilha o utilizada e qual animal foi capturado por uma determinada armadilha");
        jBLancamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLancamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLancamentoMouseExited(evt);
            }
        });
        jBLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLancamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCadEspecie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCadArmadilha, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCadArmadilha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCadEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSair)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBSair))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/1377295_545677685511440_1723756918_n.jpg"))); // NOI18N

        jMenu1.setText("Cadastros");

        jMCadEspecie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMCadEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/bullet-pata.jpg"))); // NOI18N
        jMCadEspecie.setText("Espécie");
        jMCadEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadEspecieActionPerformed(evt);
            }
        });
        jMenu1.add(jMCadEspecie);

        jMCadArmadilha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMCadArmadilha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/Pit-trap-icon.png"))); // NOI18N
        jMCadArmadilha.setText("Armadilha");
        jMCadArmadilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadArmadilhaActionPerformed(evt);
            }
        });
        jMenu1.add(jMCadArmadilha);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMConsEspecie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMConsEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/magnifier.png"))); // NOI18N
        jMConsEspecie.setText("Espécie");
        jMConsEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsEspecieActionPerformed(evt);
            }
        });
        jMenu2.add(jMConsEspecie);

        jMConsArmadilha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMConsArmadilha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/magnifier.png"))); // NOI18N
        jMConsArmadilha.setText("Armadilha");
        jMConsArmadilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsArmadilhaActionPerformed(evt);
            }
        });
        jMenu2.add(jMConsArmadilha);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");

        jMRelatorio1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMRelatorio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsEImagens/Dark-Horse-icon.png"))); // NOI18N
        jMRelatorio1.setText("Relatório 1");
        jMenu3.add(jMRelatorio1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLBarraDeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLBarraDeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadEspecieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCadEspecieMouseEntered
        jLBarraDeStatus.setText(jBCadEspecie.getToolTipText());

    }//GEN-LAST:event_jBCadEspecieMouseEntered

    private void jBCadEspecieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCadEspecieMouseExited
        jLBarraDeStatus.setText("");
    }//GEN-LAST:event_jBCadEspecieMouseExited

    private void jBCadArmadilhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCadArmadilhaMouseEntered
        jLBarraDeStatus.setText(jBCadArmadilha.getToolTipText());
    }//GEN-LAST:event_jBCadArmadilhaMouseEntered

    private void jBCadArmadilhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCadArmadilhaMouseExited
        jLBarraDeStatus.setText("");
    }//GEN-LAST:event_jBCadArmadilhaMouseExited

    private void jBLancamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLancamentoMouseEntered
        jLBarraDeStatus.setText(jBLancamento.getToolTipText());
    }//GEN-LAST:event_jBLancamentoMouseEntered

    private void jBLancamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLancamentoMouseExited
        jLBarraDeStatus.setText("");
    }//GEN-LAST:event_jBLancamentoMouseExited

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBCadEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadEspecieActionPerformed
        CadastroEspecie cadastroEspecie = new CadastroEspecie(this, true);
        cadastroEspecie.setVisible(true);
    }//GEN-LAST:event_jBCadEspecieActionPerformed

    private void jBCadArmadilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadArmadilhaActionPerformed
        CadastroArmadilha cadastroArmadilha = new CadastroArmadilha(this, true);
        cadastroArmadilha.setVisible(true);
    }//GEN-LAST:event_jBCadArmadilhaActionPerformed

    private void jBLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLancamentoActionPerformed
        Lancamento lancamento = new Lancamento(this, true);
        lancamento.setVisible(true);
    }//GEN-LAST:event_jBLancamentoActionPerformed

    private void jMCadEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadEspecieActionPerformed
        CadastroEspecie cadastroEspecie = new CadastroEspecie(this, true);
        cadastroEspecie.setVisible(true);
    }//GEN-LAST:event_jMCadEspecieActionPerformed

    private void jMCadArmadilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadArmadilhaActionPerformed
        CadastroArmadilha cadastroArmadilha = new CadastroArmadilha(this, true);
        cadastroArmadilha.setVisible(true);
    }//GEN-LAST:event_jMCadArmadilhaActionPerformed

    private void jMConsEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsEspecieActionPerformed
        ConsultaEspecie ce = new ConsultaEspecie(this, true);
        ce.setVisible(true);
    }//GEN-LAST:event_jMConsEspecieActionPerformed

    private void jMConsArmadilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsArmadilhaActionPerformed
        ConsultaArmadilha ca = new ConsultaArmadilha(this, true);
        ca.setVisible(true);
    }//GEN-LAST:event_jMConsArmadilhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadArmadilha;
    private javax.swing.JButton jBCadEspecie;
    private javax.swing.JButton jBLancamento;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLBarraDeStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMCadArmadilha;
    private javax.swing.JMenuItem jMCadEspecie;
    private javax.swing.JMenuItem jMConsArmadilha;
    private javax.swing.JMenuItem jMConsEspecie;
    private javax.swing.JMenuItem jMRelatorio1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
